apiVersion: v1
kind: Service
metadata:
  name: ml-service-lb
  labels:
    app.kubernetes.io/name: ml-service
    app.kubernetes.io/component: load-balancer
spec:
  type: LoadBalancer
  ports:
  - port: 5000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: ml-service
    app.kubernetes.io/component: server