apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service
  labels:
    app.kubernetes.io/name: ml-service
    app.kubernetes.io/component: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-service
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ml-service
        app.kubernetes.io/component: server
    spec:
      containers:
        - image: digibro/ml_service
          imagePullPolicy: Always
          name: ml-service
          ports:
            - containerPort: 5000
              name: http
          env:
            - name: ML_SERVICE_DB_HOST
              value: ml-service-db
            - name: ML_SERVICE_DB_NAME
              value: postgres
            - name: ML_SERVICE_DB_USERNAME
              value: postgres
            - name: ML_SERVICE_DB_PORT
              value: "5432"