apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-service-db
  labels:
    app.kubernetes.io/name: ml-service-db
    app.kubernetes.io/component: pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ml-service-db
      app.kubernetes.io/component: pg
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ml-service-db
        app.kubernetes.io/component: pg
    spec:
      containers:
        - name: ml-service-db
          image: postgres:10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: ml-service-db
          envFrom:
            - configMapRef:
                name: postgres-config
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres
      volumes:
        - name: postgres
          persistentVolumeClaim:
            claimName: postgres-pv-claim
